import { createOrUpdateApp, getApp } from '../strapi';
import { getActionsNTriggers, getFAQForTools, getToolDescription } from '../claude';

const removeDuplicates = (arr: string[]) => {
    return [...new Set(arr)];
}

const generateUniqueId = (app: string) => {
    return app.toLowerCase().replace(/\s/g, "_");
}




const commerceApps = [
    "Stripe",
    "Stripe",
    "Shopify",
    "Shopify",
    "Kajabi",
    "Kajabi",
    "WooCommerce",
    "WooCommerce",
    "QuickBooks Online",
    "QuickBooks Online",
    "Xero",
    "Xero",
    "ThriveCart",
    "ThriveCart",
    "Square",
    "Square",
    "Wave",
    "Wave",
    "PayPal",
    "ShipStation",
    "Ecwid by Lightspeed",
    "Gumroad",
    "Chargebee",
    "eBay",
    "lexoffice",
    "Zoho Books",
    "Ignition",
    "SamCart",
    "FreshBooks",
    "Givebutter",
    "Salla",
    "elopage",
    "Deadline Funnel",
    "Bloomerang",
    "Quotient",
    "Proposify",
    "Razorpay",
    "Zoho Invoice",
    "Planning Center",
    "MemberSpace",
    "Donorbox",
    "BigCommerce",
    "POWR Form Builder",
    "Amazon Seller Central",
    "Moneybird",
    "Better Proposals",
    "Big Cartel",
    "Plug&amp;Pay",
    "bexio",
    "GoCardless",
    "Qwilr",
    "Shippo",
    "ClickBank",
    "Magento 2.X",
    "HelloAsso",
    "Patreon",
    "You Need A Budget",
    "Revolut Business",
    "Splitwise",
    "Invoice Ninja",
    "ReCharge",
    "2Chat",
    "Lemon Squeezy",
    "Pennylane",
    "Recurly",
    "bunq",
    "Alegra",
    "Quaderno",
    "Instamojo",
    "Zoho Billing",
    "TaxDome",
    "Fundraise Up",
    "FreeAgent",
    "MoonClerk",
    "Mercury",
    "Dext",
    "Paystack",
    "Paid Memberships Pro",
    "Qonto",
    "BaseLinker",
    "Zoho Inventory",
    "Cin7 Core Inventory",
    "Customer Fields",
    "Canopy",
    "GoProposal",
    "PaintScout",
    "Service Fusion",
    "Braintree",
    "Mollie",
    "SendOwl",
    "Raisely",
    "Memberful",
    "Chargify",
    "FacturaDirecta",
    "Donately",
    "Tapfiliate",
    "RevenueHunt",
    "Ecologi",
    "Hnry",
    "Judge.me",
    "LendingPad",
    "Sharetribe",
    "SumoQuote",
    "Horoshop",
    "mallabe Currencies",
    "Soundee",
    "Payfunnels",
    "PayKickstart",
    "Virtuous CRM",
    "Zid",
    "Maropost Commerce Cloud",
    "Steady",
    "Torod",
    "Fortnox",
    "BrightManager",
    "Harness",
    "Sellfy",
    "PayPro",
    "WeTravel",
    "Novo",
    "Order Desk",
    "Senta",
    "Jumpseller",
    "Elective",
    "Give Lively",
    "Katana",
    "Refersion",
    "Giftbit",
    "Fatture in Cloud",
    "Bind ERP",
    "Shift4Shop",
    "Gift Up!",
    "Zakeke",
    "Invoiced",
    "Fattura24",
    "SureCart",
    "Mindee OCR",
    "GivingFuel",
    "Billsby",
    "Evoliz",
    "Stax",
    "Kennis.shop",
    "Popupsmart",
    "Tremendous",
    "Easyship",
    "Magento",
    "IRIS KashFlow",
    "Revv",
    "Visma eAccounting",
    "Sage Accounting",
    "Starshipit",
    "CloudCart",
    "Quipu",
    "Xola",
    "Anedot",
    "B1G1",
    "inFlow Inventory",
    "Coupon Carrier",
    "LawPay",
    "IRIS CRM",
    "Nusii Proposals",
    "Funnelish",
    "fastbill",
    "Expensify",
    "ArcSite",
    "Ponto",
    "Classy",
    "Veeqo",
    "Clicksign",
    "ChargeOver",
    "Paythen",
    "Qgiv",
    "LeadDyno",
    "QuickFile",
    "Heights Platform",
    "Mayar",
    "Amilia",
    "Selar",
    "freee",
    "EmbedSocial",
    "Anchor",
    "CS-Cart",
    "Mightycause",
    "Salsa Engage",
    "GetMyInvoices",
    "Flutterwave",
    "Stripe (Legacy)",
    "SwagUp",
    "Billit",
    "Loop Returns",
    "FYI",
    "Zoho Checkout",
    "Pleo",
    "E-Cinch",
    "Packlink PRO",
    "DPD",
    "InvoiceXpress",
    "Xama Hub",
    "Cash Flow Portal",
    "SentryKit",
    "B2B Wave",
    "Cling",
    "Fiverr Workspace",
    "Verified Reviews",
    "Paycove",
    "Portal.io",
    "Shop-Ware",
    "Libeo",
    "Invoice2go",
    "Byteplant Address Validator",
    "BTCPay Server",
    "VerifyPass",
    "Brex",
    "HirePOS",
    "MyCashflow",
    "Rotessa",
    "Moloni",
    "Churn Buster",
    "SellerCloud",
    "ikas",
    "Offorte Proposals",
    "QuoteMachine",
    "Mamo Business",
    "Airwallex",
    "CheckoutJoy",
    "Pledge",
    "Payhere",
    "Epos Now",
    "E-junkie",
    "edoobox",
    "Bkper",
    "Portals by Helium10",
    "Qoyod",
    "Shipmondo",
    "Fresh Proposals",
    "Monetizze",
    "CauseVox",
    "Sellix",
    "EditionGuard",
    "ShippyPro",
    "Asset Panda",
    "GrazeCart",
    "Confido Legal",
    "Trolley",
    "ProAbono",
    "Studiocart",
    "Prospero",
    "Skubana",
    "ViralSweep",
    "Pledge It for Charities",
    "WooDelivery",
    "Bold Commerce",
    "Seamlss",
    "Bidsketch",
    "shipcloud",
    "Veem",
    "CartonCloud",
    "Saasu",
    "Seller.Tools",
    "Maroo",
    "MAILINGWORK",
    "sticky.io",
    "Orderspace",
    "EKM",
    "FINOM",
    "MioCommerce",
    "Webshipper",
    "Back in Stock",
    "pxmo",
    "TaxJar",
    "Corpay One",
    "InvoiceBerry",
    "Daftra",
    "Calculoid",
    "Explodely",
    "Exact Online",
    "Goody",
    "Kobana (previously Boleto Simples)",
    "X-Cart",
    "PHP Point Of Sale",
    "TrackMage",
    "Chargeblast",
    "Fieldfolio",
    "Striven",
    "Fresh KDS",
    "Web Shop Manager",
    "Firm360",
    "Megaventory",
    "Amplifier",
    "SHOPLINE",
    "Cassa in Cloud",
    "Aero Workflow",
    "Stunning",
    "Boloo",
    "Respaid",
    "Back In Stock - Restock Alerts",
    "plugnpaid",
    "Hiveage",
    "QuoteCloud",
    "Quizell",
    "Glow",
    "Bright Sites",
    "Facture.net",
    "Peggy Pay",
    "Swiss QR Invoice",
    "Emotive",
    "Picreel",
    "Tree-Nation",
    "Cheddar",
    "CloudBlue Connect",
    "Piriod",
    "Digital Humani",
    "The Giving Block",
    "Popup Maker",
    "BillBjorn",
    "FoodStorm",
    "ShipEngine",
    "ServiceWorks",
    "GiveForms",
    "Space Invoices / Apollo",
    "Zahara",
    "AmeriCommerce",
    "Cash Flow Frog",
    "Turis",
    "Bolesa",
    "Run my Accounts",
    "Rev.io",
    "Groundbreaker",
    "DashNex PowerTech Store Builder",
    "Sivo",
    "GivingTech",
    "Tilkee",
    "RallyUp",
    "Offri",
    "RouteLogic",
    "Launch Cart",
    "Commerce Layer",
    "Shiptheory",
    "Reepay",
    "Vepaar",
    "Exly",
    "Reckon One",
    "PEX",
    "Jasmin",
    "AccountEdge",
    "Wisboo",
    "Storenvy",
    "ChargeKeep",
    "Sales Cookie",
    "Donation Manager RedCloud",
    "VentiPay",
    "Billit.io",
    "preezie",
    "ProcurementExpress.com",
    "Zenventory",
    "DG1",
    "Magalu",
    "Nexinvoice",
    "Paigo",
    "WiziShop",
    "Contlo",
    "Deskera",
    "Altoviz",
    "ReadyCloud Suite",
    "Everee",
    "Chaser",
    "BoxHero",
    "Contractor Commerce",
    "Zonos",
    "Zenedu",
    "SaasAnt Transactions",
    "InventoryLab",
    "ChannelDock",
    "Shopping Feed",
    "Clientary",
    "Grassrootz",
    "OnlineCheckWriter",
    "Cheddar Up",
    "CSG Forte Payments",
    "Upodi",
    "Voma",
    "Codat",
    "Sinao",
    "Jurny",
    "SimplyCOLLECT",
    "Solargraf",
    "Order Time",
    "Efactuurdirect",
    "Newtral.io",
    "Nibo",
    "YouCan",
    "Kognics",
    "DeliverLogic",
    "ReviewSender",
    "VOM",
    "PhoneRaise",
    "Xledger",
    "Shoprocket",
    "H-WEB",
    "Swag.com",
    "Instaproofs",
    "Aliaddo",
    "OneBill",
    "AbleCommerce",
    "Revi.io Reviews",
    "GoSweetSpot",
    "BizPay",
    "Payday",
    "CommerceHQ",
    "PayFacile",
    "Factomos",
    "Avify",
    "Coupon River",
    "Copperx",
    "Áskell",
    "Powershopy",
    "Rally Corp",
    "NachoNacho",
    "Bleez",
    "Hiflow",
    "Invoicing.plus",
    "HiDeliver",
    "Motor Fiscal",
    "Klutch",
    "Upbooks",
    "bidbuild",
    "Double",
    "Pinch Payments",
    "Fiskl",
    "TillyPay",
    "Well ProZ",
    "ImprintNext",
    "Enovatio",
    "VIES API",
    "Stadium",
    "Corporategift",
    "Zylvie",
    "Upzelo",
    "Re-Leased",
    "Finmei",
    "Candid Wholesale",
    "Moon Invoice",
    "FraudLabs Pro",
    "Volusion",
    "LemonInk",
    "Fintoc",
    "PriceBlocs",
    "Botkeeper",
    "Springbot",
    "Agiliron",
    "The Bookie",
    "AccountingSuite",
    "World Options",
    "Order Tagger by Shop Circle",
    "twiinworkspace",
    "TaxPlanIQ",
    "ClientPay",
    "Burq",
    "AdminPulse",
    "everbill",
    "Fast-Weigh",
    "Lista Firme",
    "Verdn",
    "Zeymo",
    "Everyware",
    "OnlineFundraising",
    "Handbid",
    "Fee Navigator",
    "BlueSnap",
    "VoucherConnect",
    "CPACharge",
    "AccountingBox",
    "Upflow",
    "Fundwave",
    "Divi Checkout",
    "GivePulse",
    "ProcureDesk",
    "MYFUNDBOX",
    "Terminal49",
    "StoreHippo",
    "LeaseHub",
    "Pro-Ledger",
    "Vetrina Live",
    "Trackfront",
    "Herv.ai",
    "PayWhirl",
    "TIDY",
    "The Stacks Plugin",
    "DeftShip",
    "Denim",
    "Siigo",
    "goTom",
    "WeSupply",
    "Jumper.ai",
    "Pelcro",
    "Carismar Commerce",
    "Online Car Store",
    "ExRt.Live",
    "UpperBee",
    "Blink",
    "Propago",
    "VERIFYiQ",
    "Dropmatix",
    "PayRequest",
    "Procys",
    "Gaviti",
    "NuMetric",
    "Finolog",
    "Qawafil",
    "MyCarTracks",
    "Woovi",
    "RZQ",
    "FireBox",
    "Billplz",
    "Overflow",
    "Greenspark",
    "AuditCase",
    "Ordermate",
    "Keysender",
    "Zuora",
    "Lamha",
    "Biztera",
    "Turbine",
    "Custom Gateway OMS",
    "Ridehire",
    "QuickBooks Commerce",
    "Apparound",
    "Lengow",
    "CoinGate",
    "Elliot",
    "NetLicensing",
    "towio",
    "GoFileRoom",
    "Eshopbox",
    "Cognitive Invoice",
    "Route the Service Platform",
    "HotShp",
    "Uncommon Giving",
    "Direct Debit",
    "Upnid",
    "Invoice Crowd",
    "Gigrove",
    "Nomisma",
    "SubSocket",
    "Dola",
    "Contalink",
    "Anduin Fund Subscription",
    "ZarMoney",
    "Auxilia",
    "Simply Budget",
    "Payload",
    "4Pay",
    "OneWayLoyalty",
    "SpruceJoy",
    "Pomelo Pay",
    "Fiddle",
    "Cobiro",
    "Expensya",
    "QuoteRules",
    "Product List Genie",
    "Matajer",
    "Authvia",
    "tuGerente",
    "Andpay",
    "Sellgo",
    "cube-usa",
    "KlimAPI",
    "Smarty Accounting",
    "legodesk",
    "SaleDrum",
    "Menaflow",
    "DoJiggy",
    "AffiniPay",
    "Reloadly",
    "Rewix",
    "Billed",
    "Subamplify",
    "Storeplum",
    "Commerceup",
    "PaySolution Asia",
    "Journalize.io",
    "Customer Tags &amp; Segments by Shop Circle",
    "SnackMagic",
    "BP Pay",
    "SAI360 GRC",
    "autoRetouch",
    "Evergiving",
    "Twig Business",
    "Life Peaks",
    "Peblo",
    "Blinksale",
    "GivingX.com",
    "QCommission",
    "OrderForms",
    "Lancerkit",
    "Riseact",
    "Review Generator (AI)",
    "MoneyTool.io",
    "Intelligent Billing",
    "Community Funded",
    "Sphere Pay",
    "aamarPay",
    "Retailed",
    "faktoora",
    "Gridizen",
    "Verificare TVA",
    "Edens",
    "ZOEY by Tekton Billing",
    "Nas.io",
    "Jungle Scout",
    "ScanPay",
    "Search Agora",
    "Joltz: Bitcoin Rewards",
    "Sage Intacct",
    "Mainstack",
    "BrightPlans",
    "Spreedly",
    "Dwolla",
    "Authorize.net",
    "Unleashed Software",
    "TaskRabbit",
    "Spree",
    "Shipwire",
    "Foxycart",
    "Etsy",
    "Airbnb",
    "Myob",
    "1Shoppingcart",
    "Lightspeed",
    "AliExpress",
    "Floify",
    "EasyPost",
    "Ecomdash",
    "PocketSmith",
    "CDK Global",
    "FranConnect",
    "Cardconnect",
    "Gear Launch",
    "Cielo",
    "Payfirma",
    "Ultracart",
    "Cratejoy"
]

const TOOLS_TO_CREATE = [
    {
        key: "google-maps",
        name: "Google Maps",
        logo: "https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png",
        website_link: "https://www.google.com/maps",
        description: "Google Maps is a web service that allows users to search for and view maps, including directions, street view, and other related information."
    }
]

// DON'T CHANGE THE BELOW CODE
async function main() {
    const uniqueApps = removeDuplicates(commerceApps);
    const batchSize = 7;
    
    for (let i = 0; i < uniqueApps.length; i += batchSize) {
        const batch = uniqueApps.slice(i, i + batchSize);
        await Promise.all(batch.map(app => createNewTool(app)));
    }

}

const createNewTool = async (app: any) => {
    const { description, website_link } = await getToolDescription(app);

    const toolDetails = {
        key: generateUniqueId(app),
        name: app,
        logo: null,
        website_link: website_link,
        description: description
    }
    const parsedActions: ActionOrTrigger[] = []; // Explicitly type the array
    const parsedTriggers: ActionOrTrigger[] = []; // Explicitly type the array

    const strapiApp = await getApp(toolDetails.key);
    let FAQ: { question: string, answer: string }[] = [];
    if (!strapiApp) {
        //@ts-ignore
        const [actionsNTriggers] = await Promise.all([
            getActionsNTriggers(toolDetails.key),
        ]);
        console.log(actionsNTriggers)

        //@ts-ignore
        for (const actionOrTrigger of actionsNTriggers.actions_triggers) {
            if (actionOrTrigger.type === "action") {
                parsedActions.push({
                    name: actionOrTrigger.name,
                    desc: actionOrTrigger.description?.substring(0, 200),
                    tag: "",
                    unique_id: actionOrTrigger.unique_id
                });
            }
            if (actionOrTrigger.type === "trigger") {
                parsedTriggers.push({
                    name: actionOrTrigger.name,
                    unique_id: actionOrTrigger.unique_id,
                    desc: actionOrTrigger.description?.substring(0, 200),
                    tag: "",
                });
            }
        }
        // FAQ = await getFAQForTools(app.key, {});
    }
    if (!strapiApp?.id){
    await createOrUpdateApp({
        name: toolDetails.name,
        logo: toolDetails.logo || "",
        unique_id: toolDetails.key,
        description: toolDetails.description,
        tool_type: 'api',
        website_link: toolDetails.website_link,
        playground_config: "",
        actions: [],
        triggers: [],
        examples: [],
        tags: [58],
        //@ts-ignore
        ...(!strapiApp?.id ? {
            FAQ: FAQ,
            actions: parsedActions as ActionOrTrigger[],
            triggers: parsedTriggers as ActionOrTrigger[],
        } : {

        })
    }, strapiApp?.id)
        console.log("App created/updated", toolDetails.key);
}else{
    console.log("App already exists", toolDetails.key);
}

   
}

main();

type ActionOrTrigger = {
    name: string;
    desc: string;
    tag: string;
    unique_id: string;
};